---
language: python
python: "2.7"
dist: precise
sudo: required

env:
  - ANSIBLE_VERSION=2.0.1.0
  - ANSIBLE_VERSION=2.7.10
  - ANSIBLE_VERSION=latest

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --syntax-check

  # Run the role
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local

  # Check git config
  - git config --list | grep gitmessage
  - git config --list | grep excludesfile
  - git config --list | grep -e editor -e commit -e push -e pull

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
